name: venv_redes
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bidict=0.23.1
  - blinker=1.9.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - click=8.1.8
  - flask=3.1.0
  - flask-socketio=5.5.1
  - h11=0.16.0
  - importlib-metadata=8.6.1
  - itsdangerous=2.2.0
  - jinja2=3.1.6
  - ld_impl_linux-64=2.43
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libsqlite=3.49.2
  - libuuid=2.38.1
  - libzlib=1.3.1
  - markupsafe=3.0.2
  - ncurses=6.5
  - openssl=3.5.0
  - pip=25.1.1
  - python=3.13.3
  - python-dotenv=1.1.0
  - python-engineio=4.12.0
  - python-socketio=5.13.0
  - python_abi=3.13
  - readline=8.2
  - simple-websocket=1.1.0
  - tk=8.6.13
  - typing_extensions=4.13.2
  - tzdata=2025b
  - werkzeug=3.1.3
  - wsproto=1.2.0
  - zipp=3.21.0
